//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PineCone.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PineCone.Resources.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Item of type &apos;{0}&apos; has no Id member specified. A Guid or Int property named &apos;Id&apos; was expected..
        /// </summary>
        internal static string AutoSchemaBuilder_MissingIdMember {
            get {
                return ResourceManager.GetString("AutoSchemaBuilder_MissingIdMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Item of type &apos;{0}&apos; has no members that are indexable. There&apos;s no point in treating items that has nothing to index..
        /// </summary>
        internal static string AutoSchemaBuilder_MissingIndexableMembers {
            get {
                return ResourceManager.GetString("AutoSchemaBuilder_MissingIndexableMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The id property: &apos;{0}&apos;; is not of suported type. Only Guid and Int is accepted..
        /// </summary>
        internal static string AutoSchemaBuilder_UnsupportedIdAccessorType {
            get {
                return ResourceManager.GetString("AutoSchemaBuilder_UnsupportedIdAccessorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id values must lie on the root object..
        /// </summary>
        internal static string IdAccessor_GetIdValue_InvalidLevel {
            get {
                return ResourceManager.GetString("IdAccessor_GetIdValue_InvalidLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Property.PropertyType &apos;{0}&apos; is not supported by the IdAccessor..
        /// </summary>
        internal static string IdAccessor_UnsupportedPropertyType {
            get {
                return ResourceManager.GetString("IdAccessor_UnsupportedPropertyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Unique-index found for &apos;{0}&apos;.\r\nStructureId: &apos;{1}&apos;;Name: &apos;{2}&apos;;Value: &apos;{3}&apos;;.
        /// </summary>
        internal static string Structure_DuplicateUniques {
            get {
                return ResourceManager.GetString("Structure_DuplicateUniques", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must provide an unique guid to the GuidId..
        /// </summary>
        internal static string StructureId_GuidIsMissingValue {
            get {
                return ResourceManager.GetString("StructureId_GuidIsMissingValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must provide a positive identity..
        /// </summary>
        internal static string StructureId_IdentityIsOutOfRange {
            get {
                return ResourceManager.GetString("StructureId_IdentityIsOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When using Guids the Id-property of the entity must be assigned before structure is created..
        /// </summary>
        internal static string StructureIdFactory_MissingGuidValue {
            get {
                return ResourceManager.GetString("StructureIdFactory_MissingGuidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When using Identities the Id-property of the entity must be assigned before structure is created..
        /// </summary>
        internal static string StructureIdFactory_MissingIdentityValue {
            get {
                return ResourceManager.GetString("StructureIdFactory_MissingIdentityValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The identity type: &apos;{0}&apos; is not supported..
        /// </summary>
        internal static string StructureIdFactory_UnSupportedIdentityType {
            get {
                return ResourceManager.GetString("StructureIdFactory_UnSupportedIdentityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only strings and valuetypes can be stored as indexes..
        /// </summary>
        internal static string StructureIndex_ValueArgument_IncorrectType {
            get {
                return ResourceManager.GetString("StructureIndex_ValueArgument_IncorrectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Unique index &apos;{0}&apos;:&apos;{1}&apos; is evaluated to Null. This is not alowed..
        /// </summary>
        internal static string StructureIndexesFactory_UniqueIndex_IsNull {
            get {
                return ResourceManager.GetString("StructureIndexesFactory_UniqueIndex_IsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cant apply Unique on a member that is not of a simple type e.g. (int, string, bool) etc..
        /// </summary>
        internal static string StructureProperty_Ctor_UniqueOnNonSimpleType {
            get {
                return ResourceManager.GetString("StructureProperty_Ctor_UniqueOnNonSimpleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The UniqueModes &apos;{0}&apos; is unknow and cant be mapped..
        /// </summary>
        internal static string UniqueModesCantBeMapped {
            get {
                return ResourceManager.GetString("UniqueModesCantBeMapped", resourceCulture);
            }
        }
    }
}
